MySkincareFaves/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('', include('common.urls')),
]

users/urls.py
from django.urls import path, include

from users.views import CustomLoginView, UserRegisterView, UserLogoutView, UserUpdateView, \
    UserDeleteView, details_user

urlpatterns = (
    path('login/', CustomLoginView.as_view(), name='login_user'),
    path('register/', UserRegisterView.as_view(), name='register_user'),
    path('logout/', UserLogoutView.as_view(), name='logout_user'),
    path('<int:pk>/', include([
        path('', details_user, name='details_user'),
        path('edit/', UserUpdateView.as_view(), name='update_user'),
        path('delete/', UserDeleteView.as_view(), name='delete_user'),
    ]))
)

products/models.py
from django.db import models
from django.utils import timezone

from users.models import User


class Product(models.Model):
    PRODUCT_TYPE_CHOICES = [
        ('cleanser', 'Cleanser'),
        ('moisturizer', 'Moisturizer'),
        ('night cream', 'Night Cream'),
        ('serum', 'Serum'),
        ('toner', 'Toner'),
        ('mask', 'Mask'),
        ('sunscreen', 'Sunscreen'),
        ('eye cream', 'Eye Cream'),
        ('other', 'Other'),
    ]
    name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
    )
    product_type = models.CharField(
        max_length=20,
        choices=PRODUCT_TYPE_CHOICES,
        null=False,
        blank=False,
    )
    package_size_in_milliliters = models.IntegerField(
        blank=False,
        null=False,
        default=0,
    )
    description = models.TextField(
        null=True,
        blank=True,
    )
    key_ingredients = models.TextField(
        null=True,
        blank=True,
    )
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        unique_together = ('user', 'product')

    def __str__(self):
        return f'{self.user.username} - {self.product.name}'


class Review(models.Model):
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        related_name='reviews',
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    created_at = models.DateTimeField(
        default=timezone.now,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'product'], name='unique_review'
            )
        ]

    def __str__(self):
        return f"Review by {self.user} on {self.product.name}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css?fbclid=IwAR2iM9Vv3ypA56f6kjp69EmcLsi7u-OKRrEL8hCcXkq9iePpT0Q-9OnNssw"/>    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}My Skincare Faves{% endblock %}</title>
</head>

<body style='background-image: url("{% static "images/Background_image.jpg" %}")'>

<div class="wrapper">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'images/logo.png' %}" alt="Flaticon Icon">
                    <span class="title-text">My Skincare Faves</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    {% include 'nav.html' %}
                </div>
            </div>
        </nav>
    </header>

    <main class="flex-fill">
        {% block page_content %}
        {% endblock %}
    </main>
</div>

<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">© <span id="currentYear"></span> My Skincare Faves</span>
    </div>
</footer>

<script>
    var currentYear = new Date().getFullYear();
    document.getElementById("currentYear").innerHTML = currentYear;
</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

templates/catalogue.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block page_content %}


<div class="container mt-5">
    <h1 class="catalogue-title">My Skincare Catalogue</h1>
    
    <form method="get" class="sort-form mb-3 align-items-center">
        <label for="user_sort_by" class="mr-2">Sort by:</label>
        <select name="user_sort_by" id="user_sort_by" class="form-control mr-3" onchange="this.form.submit()">
            <option value="name" {% if user_sort_by == 'name' %}selected{% endif %}>Name</option>
            <option value="price" {% if user_sort_by == 'price' %}selected{% endif %}>Price</option>
            <option value="type" {% if user_sort_by == 'type' %}selected{% endif %}>Type</option>
            <option value="likes" {% if user_sort_by == 'likes' %}selected{% endif %}>Likes</option>
        </select>
    
        <label for="user_order" class="mr-2">Order</label>
        <select name="user_order" id="user_order" class="form-control mr-3" onchange="this.form.submit()">
            <option value="asc" {% if user_order == 'asc' %}selected{% endif %}>Ascending</option>
            <option value="desc" {% if user_order == 'desc' %}selected{% endif %}>Descending</option>
        </select>
    </form>    

    <div class="catalogue-table">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Size (ml)</th>
                    <th scope="col">Price (BGN)</th>
                    <th scope="col">Likes</th>
                </tr>
            </thead>
            <tbody>
                {% for product in user_products %}
                <tr>
                    <td><a href="{% url 'product_details' product.pk %}">{{ product.name }}</a></td>
                    <td>{{ product.get_product_type_display }}</td>
                    <td>{{ product.package_size_in_milliliters }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.like_count }}</td>
                    <td>
                        <a href="{% url 'review_product' product.pk %}" class="btn btn-custom">Leave Review</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="text-center mt-3">
        <a href="{% url 'add_product' %}" class="btn btn-primary">Add another product</a>
    </div>

    <div class="catalogue-table mt-5">
    <h2 class="catalogue-title">Other Users' Favorite Products</h2>
    
    <form method="get" class="sort-form mb-3 align-items-center">
        <label for="other_sort_by" class="mr-2">Sort by:</label>
        <select name="other_sort_by" id="other_sort_by" class="form-control mr-3" onchange="this.form.submit()">
            <option value="name" {% if other_sort_by == 'name' %}selected{% endif %}>Name</option>
            <option value="price" {% if other_sort_by == 'price' %}selected{% endif %}>Price</option>
            <option value="type" {% if other_sort_by == 'type' %}selected{% endif %}>Type</option>
            <option value="likes" {% if other_sort_by == 'likes' %}selected{% endif %}>Likes</option>
        </select>
    
        <label for="other_order" class="mr-2">Order</label>
        <select name="other_order" id="other_order" class="form-control mr-3" onchange="this.form.submit()">
            <option value="asc" {% if other_order == 'asc' %}selected{% endif %}>Ascending</option>
            <option value="desc" {% if other_order == 'desc' %}selected{% endif %}>Descending</option>
        </select>
    </form>     
    
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Size (ml)</th>
                    <th scope="col">Price (BGN)</th>
                    <th scope="col">Likes</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for product in other_users_products %}
                <tr>
                    <td><a href="{% url 'product_details' product.pk %}">{{ product.name }}</a></td>
                    <td>{{ product.get_product_type_display }}</td>
                    <td>{{ product.package_size_in_milliliters }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.like_count }}</td>
                    <td>
                        <form action="{% url 'like_product' product.pk %}" method="post">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-info">
                                {% if product.id in liked_products %}
                                        Unlike
                                {% else %}
                                        Like
                                {% endif %}
                            </button>
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'review_product' product.pk %}" class="btn btn-custom">Leave Review</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <div class="container">
        <div class="row justify-content-center align-items-center" style="min-height: 80vh">
            <div class="col-9 text-center">
                <h1>Welcome to your favorite skincare products!</h1>
                <h4>Add them to your catalogue and enjoy!</h4>
            </div>
        </div>
    </div>
{% endblock %}

templates/nav.html
{% load static %}
{% block page_content %}
    
<div class="collapse navbar-collapse">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">
                <i class="fas fa-home"></i>Home</a>
        </li>
        
        {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login_user' %}">
                    <i class="fas fa-sign-in-alt"></i>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register_user' %}">
                    <i class="fas fa-user-plus"></i>Register</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'details_user' request.user.pk %}">
                    <i class="fas fa-user"></i>Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogue' %}">
                    <i class="fas fa-book"></i>My catalogue</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_product' %}">
                    <i class="fas fa-plus"></i>Add product</a>
            </li>
            <li class="nav-item">
                <form method="post" action="{% url 'logout_user' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link btn btn-link">
                    <i class="fas fa-sign-out-alt"></i>Logout
                    </button>
                </form>
            </li>
        
        {% endif %}
    </ul>
</div>
    
{% endblock %}